name: build_pubspec
description: Extract pubspec data
version: 1.4.0

environment:
  sdk: ^3.9.2

dependencies:
  build: ^4.0.2
  pubspec_parse: ^1.5.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.21.0
